Game-as-a-Service/Game-Lobby-Web

README.md

Docs: Add the contributor list.

---

AUTHORS

feat : add author zilongrrr

---

AUTHORS

feat: add author

---

configs/axios.ts
package.json
pages/_app.tsx
pages/api/internal/[...slug].tsx
requests/request.ts
shared/containers/provider/AxiosProvider.tsx
shared/contexts/AxiosContext.tsx
shared/hooks/context/useAxios.ts
shared/hooks/useRequest.ts
yarn.lock

- add http client package: axios & swr
- add api proxy internal route & http-proxy-middleware package (remaining work: add backend endpoint in env)
- add axios context & provider container & hook
- add http request wrapper

feat: http-client

---

next.config.js
package-lock.json
package.json
pages/index.tsx
shared/components/Cover/cover.test.tsx
shared/components/Cover/index.tsx
styles/global.css
utils/getBase64Image.js
yarn.lock

feat: cover

---

lib/utils.ts
package.json
yarn.lock

Add util function for usage with clsx & tailwindcss merge
```javascript
import { cn } from "@/lib/utils"
const ComponentA = ({ className }) => {
...
return (
<div className={cn("m-0 pl-2", { "pl-4": pattern !== "strategy" }, classNames)}>Some things</div>
)
}
```

➕ feat: add util func for clsx & tailwind-merge

---

.github/workflows/build-and-deploy.yaml

- Avoid unnecessary push
- Deploy only if push to main
-
-

fix: deploy only while push to main

---

shared/components/Avatar/Avatar.test.tsx
shared/components/Avatar/Avatar.tsx
shared/components/Avatar/index.tsx

- Implement the `Avatar` component.

feat: avatar

---

.github/workflows/build-and-deploy.yaml

- Trigger Github actions manually
- Add condition in `Build and Test and Deploy to AWS EC2` jobs
-
-

fix(cicd): trigger

---

shared/components/Badge/Badge.tsx
shared/components/Badge/badge.test.tsx
shared/components/Badge/index.ts

feat: badge

---

pages/_app.tsx
pages/index.tsx
shared/components/Modal/ModalManager/index.tsx
shared/components/Modal/ModalManager/src/Modal.types.ts
shared/components/Modal/ModalManager/src/ModalManager.tsx
shared/components/Modal/ModalManager/src/ModalManagerBase.tsx
shared/components/Modal/ModalManager/src/ModalStore.tsx
shared/components/Modal/ModalManager/src/utils.tsx
shared/components/Modal/example/ModalExample1.tsx
shared/components/Modal/example/ModalExample2.tsx
shared/components/Modal/example/ModalExample3.tsx
shared/components/Modal/index.tsx

add modal component and modal manager feature, please refer to the usage in pages/index.tsx file.
✅ Closes: https://github.com/Game-as-a-Service/Game-Lobby/issues/28
-
-
-
-

feat: 🎸 modal

---

shared/components/Icon/Icon.tsx
shared/components/Icon/group/arrow-right.ts
shared/components/Icon/icon.test.tsx
shared/components/Icon/index.tsx
shared/components/Icon/types/types.ts

feat: icon

---

shared/components/Input/Input.tsx
shared/components/Input/index.tsx
shared/components/Input/input.test.tsx

feat: ✨ input

---

shared/components/Tabs/Tab.test.tsx
shared/components/Tabs/Tab.tsx
shared/components/Tabs/Tabs.test.tsx
shared/components/Tabs/Tabs.tsx
shared/components/Tabs/index.tsx

feat: tabs

---

shared/components/SearchBar/SearchBar.tsx
shared/components/SearchBar/index.tsx
shared/components/SearchBar/searchBar.test.tsx

- To implement the basic style and functionality of the search bar.
- Merge `feature/button` and `feature/input` into `feature/search-bar`
- Added the search bar directory, component, and unit tests.
- Tested the basic functionality of the search feature.
- Close: #30

feat: ✨ search bar

---

shared/components/Modalow/Body.tsx
shared/components/Modalow/Example.tsx
shared/components/Modalow/Footer.tsx
shared/components/Modalow/Header.tsx
shared/components/Modalow/Icon.tsx
shared/components/Modalow/Mask.tsx
shared/components/Modalow/Modalow.stories.tsx
shared/components/Modalow/Modalow.tsx
shared/components/Modalow/Portal.tsx
shared/components/Modalow/index.tsx
shared/components/Modalow/modal.module.css
shared/components/Modalow/modalow.test.tsx

refactor: modal

---

package.json
yarn.lock

- currently, the build step will fail because of type
- may be issues of `yarn` and `@types/react`
- update `@types/react` to latest version and add resolution section will solve this issue
-
-
-

fix: build error cause by type

---

.github/workflows/build-and-deploy.yaml
package.json
yarn.lock

- Unmet peer dependencies
- Add `@babel/core` resolution
- Yarn update ` css-loader`、`node-polyfill-webpack-plugin`、`postcss-loader`、`sass-loader` and `style-loader`
-
-

chore: storybook unmet peer dependencies

---

.storybook/preview.ts
shared/components/Input/Input.tsx
shared/components/Input/input.stories.tsx
shared/components/Input/input.test.tsx

- Added of input's Storybook documentation.
- Refactor of input style.
- Added max length prop
- Added input Storybook
- Added Storybook default background of dark
- unit test on the input
- change input style
- Close: #80

doc: 📝 add input story book

---

shared/components/SearchBar/SearchBar.tsx
shared/components/SearchBar/searchBar.stories.tsx
shared/components/SearchBar/searchBar.test.tsx

- Added of searchBar's Storybook documentation.
- Refactor of search bar style.
- Removing unnecessary onEnter and Composition event.
- Added search bar Storybook
- unit test on the search bar
- change search bar style
- Close: #82

doc: 📝 add search bar story book

---

shared/components/Badge/Badge.stories.tsx
shared/components/Badge/Badge.tsx

- Added Badge component's storybook.
- Refactored the Badge component to export const variant.
- Fixed logical error on badge's hidden action.
- Create Badge .stories.tsx.
- Refactor Badge .tsx.
-
- #107

doc: added badge storybook

---

components/lobby/CreateRoomModal/GameListModal/GameListModal.tsx
components/lobby/CreateRoomModal/GameListModal/gameListModal.module.css
components/rooms/RoomChatroom/ChatMessage.test.tsx
components/rooms/RoomChatroom/ChatMessage.tsx
components/rooms/RoomChatroom/RoomChatroom.test.tsx
components/rooms/RoomChatroom/RoomChatroom.tsx
components/rooms/RoomChatroom/index.ts
containers/provider/ChatroomProvider.tsx
contexts/ChatroomContext.tsx
hooks/context/useChatroom.ts
package.json
pages/_app.tsx
pages/api/mock/socket.ts
pages/rooms/[roomId]/index.tsx
styles/global.css
yarn.lock

- Implement chatroom in Room page
- Install devDependencies: ws, types/ws 
- Add Components: ChatMessage, RoomChatroom
- Add Context hook: useChatroom
- Add mock socket server
- Add global css class: scrollbar
- Replace scrollbar class with global class in GameListModal component
- Unit-test: ChatMessage, RoomChatroom
- #101

feat: chatroom in room page via websocket

---

pages/api/internal/[...slug].tsx

fix: api route

---

components/lobby/CreateRoomModal/CreateRoomModal.tsx
components/shared/PasswordField/PasswordField.stories.tsx
components/shared/PasswordField/PasswordField.test.tsx
components/shared/PasswordField/PasswordField.tsx
components/shared/PasswordField/index.ts

- The "Password Field" component needed to be extracted from the `components\lobby\CreateRoomModal` due to cluttered logic and the potential for future use in other scenarios.
- Added new shared component `PasswordField`.
- Added the storybook and test of `PasswordField`.
- Refactored the `CreateRoomModal.tsx` to extract password input logic.
-
- #150

feat: password field component

---

components/lobby/EnterPrivateRoomModal/EnterPrivateRoomModal.tsx
components/lobby/UserInfoModal.tsx
components/rooms/RoomCard.tsx
components/rooms/RoomsList.tsx
hooks/useRequest.ts
pages/login.tsx
tailwind.config.js

- Enhance user experience when calling API
- use request add toast
- fix api error logout
- remove call login alert
- fix tailwindCSS color
-
- Close: #167 
- Close: #168

✨ feat: use request add toast and fix bug

---

components/rooms/RoomCard.tsx
components/rooms/RoomsList.tsx
components/shared/Chat/ChatMessage.tsx
components/shared/Header.tsx
components/util/api-history/ApiHistoryList.tsx
containers/layout/AppLayout.tsx
pages/rooms.tsx
styles/global.css
tailwind.config.js

- Added AppLayout
- Adjusted css for RWD
- Adjusted ApiHistoryList to avoid overlay on Header
- Closed #178

👁️   fix: rooms add layout

---

pages/rooms/[roomId]/index.tsx
requests/rooms/index.ts

- Added leaveRoom function and request API
-
-
- Closed #191

👁️ feat: leave room

---

components/shared/Chat/index.tsx
components/shared/Portal/Portal.tsx
components/shared/Toast/CtxToastQueue.tsx
components/shared/Toast/ToastQueueContext.tsx
pages/_document.tsx

- Integrated the component used `createPortal` with `Portal` component.
- `components/shared/Toast/CtxToastQueue.tsx` & `ToastQueueContext.tsx` made by @Dandelion64.
- `components/shared/Chat/index.tsx` made by @bxbdev.
-
- #187

refactor: integrated component with portal

---

hooks/usePopup.tsx

- Fixing the bug causing flashing of popup when toast context state changes
- Wrap hook functions with useCallback
- Wrap Popup component with useMemo
- Manual testing
- #220 
於 #220 的留言有提到輸入錯誤密碼後，錯誤訊息的彈窗會出現又立即消失的議題，原本打算重刻一組與 `Modalow` 一模一樣的樣式，但後來覺得這樣有點重工，想說看是不是可以調整 #219 進入私有房間的流程，來解決議題。
調整的方式為在原本 fetchRoomEntry 中， 將 .finally 區塊中的 setSelectedRoom(undefined) 移除，讓使用者即使輸入錯誤訊息，依然可以保留輸入的密碼彈窗，允許再次輸入。
以上說明，可以再討論，感謝。

fix: reslove flashing-popup issue#220

---

components/shared/Sidebar.tsx

- Fix Sidebar links to enable navigation
- Embed links in the Sidebar component
-
- #183

fix: sidebar links

---

components/shared/Header.tsx
components/shared/Sidebar.tsx
containers/room/RoomListView.tsx

- remove anything temporarily useless layouts, functions
- remove add/sub 10 pages buttons in rooms page
- remove useless text and actions in Header
- remove news in Sidebar
-
- #237

fix: #237 remove anything temporarily useless 

---

configs/i18nConfigs.ts
containers/room/RoomListView.tsx
next-i18next.config.js
next.config.js
package.json
pages/_app.tsx
pages/index.tsx
pages/rooms.tsx
public/locales/zh-tw/rooms.json
yarn.lock

- Set i18n environment
- Added zh-TW/rooms.json translation file
-
-
- Closed #236

feat: i18n

---

mocks/room.ts
pages/api/mock/rooms/[roomId]/index.ts
pages/rooms/[roomId]/index.tsx
requests/rooms/index.ts
yarn.lock

- Updated mock_roomInfo
- Added handleStart function
- Added startGame API
-
-
- Closed #238

feat: start game

---

package.json
yarn.lock

Reverts Game-as-a-Service/Game-Lobby-Web#251

revert: [RENOVATE-BOT] Update dependencies (non-major)"

---

docker/Dockerfile.production
next-i18next.config.js

- i18n not working in production
-
-
- Close #291

🐛 fix i18n not working in production issue

---

components/rooms/GameWindow.test.tsx
components/rooms/GameWindow.tsx
pages/api/mock/rooms.ts
pages/api/mock/socketio.ts
pages/rooms/[roomId]/index.tsx

- Implement game start feature after received GAME_STARTED message from socket.IO
- Add `GameWindow` component with HTML5 iframe tag
- Combined the gameUrl and token as the source for the `GameWindow`  after received gameUrl from socket.IO server
- Modify the mock response data of getRooms API
- Unit-test : `GameWindow.test.tsx` 
- Closes #282
- Closes #283

feat: opening gameUrl with token via Iframe

---

components/lobby/FastJoinButton.tsx
pages/api/internal/[...slug].tsx
pages/api/mock/games.ts
pages/api/mock/rooms/fastJoin/index.tsx
pages/index.tsx
requests/rooms/index.ts

- Implement fast join button
- Add fast join button in `FastJoinButton`
- Add new request `fastJoinGameEndpoint`
- Change the response data of the `getAllGamesEndpoint`
-
- #266

feat: fast join room

---

components/rooms/RoomChatroom/ChatMessage.test.tsx
components/rooms/RoomChatroom/ChatMessage.tsx
components/rooms/RoomChatroom/RoomChatroom.tsx
components/rooms/RoomChatroom/index.ts
containers/provider/ChatroomProvider.tsx
pages/api/mock/socketio.ts

- #274 
- Change MessageType and every codes that related
-
- closes #274

refactor: modified MessageType

---

.github/workflows/build-and-deploy-storybook.yaml

- update node.js version for automatic Storybook deployment
- Github actions
-
-

💚 fix: update node.js version for automatic Storybook deployment

---

components/rooms/RoomChatroom/RoomChatroom.tsx

- The input box in the chat room does not display the entered text.
- Chat room style
-
- Close #368

💄 fix chat room color

---

pages/rooms/[roomId]/index.tsx

-
- fix game end not async room info bug
- room page
- Close Game-as-a-Service/Lobby-Platform-Service#206

fix: game end not getting the correct room status bug

---

components/shared/Chat/v2/Chat.tsx
components/shared/Chat/v2/ChatHeader.tsx
components/shared/Header.tsx
components/shared/SearchBar/SearchBar.tsx
components/shared/Sidebar.tsx
containers/layout/AppLayout.tsx
pages/_document.tsx
pages/index.tsx
tailwind.config.js

- add search bar and chat component to layout
- search bar component style
- chat component style
- app layout
- 
-

feature: update layout v2

---

components/shared/Carousel/v2/Carousel.stories.tsx
components/shared/Carousel/v2/Carousel.tsx
components/shared/Carousel/v2/index.tsx
components/shared/Chat/v2/Chat.tsx
components/shared/Icon/v2/icons/index.ts
pages/index.tsx
tailwind.config.js

- carousel v2 component
- carousel v2 component
- home page
- 
- #349

feature: carousel v2 component

---

.github/workflows/auto-label.yaml

- Github actions: auto label - add security label
- Github actions
- none
- none

feat: add security label

---

.github/workflows/build-and-deploy-storybook.yaml

feature: Update Node version to 20.19.4 in Storybook workflow
