Game-as-a-Service/Game-Lobby-Web

shared/components/Modalow/Body.tsx, shared/components/Modalow/Modalow.tsx
- Body.tsx 中 dialogContentClassName 誤加了 flex flex-auto class 導致 children 樣式異常。
- Modalow.tsx 未遵循設計稿 Dialog 位置。
| Before | After |
|-----|-------|
| <img width="415" alt="image" src="https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/a79b4020-0158-45dc-89a0-cb960fd135ce">| <img width="416" alt="image" src="https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/eaa74890-1df5-4188-8ff4-fa7d465e158b"> |
- 將Body.tsx 內 dialogContentClassName 中的 flex flex-auto 移除。
- 對 Modalow.tsx 內的 dialogContainerClassName 增加了 top-1/2 -translate-y-1/2 class 已符合樣式。
-
- #85
=> fix: Adjusted modal style

.dockerignore, docker/Dockerfile.production, next.config.js
- original production Dockerfile can not build successfully because it run build before copy the content
- after change the order, we can build successfully, but I found that the image size is too big (3.xxGB)
- I choose to use [multi-stage build](https://docs.docker.com/build/building/multi-stage/) to minimize the image size, and the result is as below
Before optimization: 3.4 GB 🥵
After optimization: 871 MB 🥺
It is almost 4 times smaller.
- add `next.config.js`, I think we may need this file to add some config in the near future. In this PR, we set lint to ignoreDuringBuilds because we plan to run lint in pre-commit step, which can make build step quicker
-
- Although we do not use docker for deployment now, maybe we will need it if we migrate to k8s or ECS in the future
-
=> feat: production dockerfile optimization

.github/workflows/build-and-deploy.yaml, .github/workflows/ci.yaml
- The original unified workflow has been broken down into multiple jobs: `build`, `test`, and `lint`. Both `lint` and `test` jobs are designed to run in parallel once the `build` job completes. This arrangement offers the benefit of maximizing pipeline execution speed in the future when there are other steps that also depend on the results of the build job.
- By utilizing the cache action and using the hash values of `yarn.lock` and the source code (ts, tsx, js, jsx) as the cache keys, theoretically, both `lint` and `test` jobs can make use of the cache created during the build step, eliminating the need to reinstall dependencies.
| lint (cache hit) | test (cache hit) |
|-----|-------|
| ![圖片](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/35811214/7db3e98f-1be3-467b-8298-0086a …
=> refactor: extract pull-request workflow to multi jobs & restore cache

mocks/auth.ts, pages/api/mock/auth/login.ts, pages/api/mock/auth/token.ts, pages/api/mock/user/me.ts, requests/auth/auth.ts, requests/auth/user.ts, shared/containers/provider/AuthProvider.tsx, shared/containers/util/Startup.tsx, shared/contexts/AuthContext.tsx, shared/hooks/useRequest.ts, shared/hooks/useUser.ts
- mock example: `mocks` folder set mock data provide to mock api route
- get current user info by header bearer token
-
-
-
=> feat: current user info & mock example

.github/workflows/build-and-deploy.yaml
- The current workflow of deployment sometimes gets stuck, which consequently causes other jobs to be queued.
- add [job timeout](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) 
-
-
=> fix: add deploy job timeout

.github/workflows/build-and-deploy.yaml
- EC2 install too many deps, so it frequently install until timeout
- Use `--production` flag to only install production dependencies, and neglect devDependencies
-
-
=> fix: only install prod deps in ec2

shared/components/Avatar/Avatar.stories.tsx, shared/components/Avatar/Avatar.tsx
- Add storybook documentation for the `Avatar` component to demonstrate the usage and variants.
- Refactor the `Avatar` component to enable the square shape.
- Create `Avatar.stories.tsx`.
- Refactor `Avatar.tsx.`
-
-
=> doc: add avatar storybook

components/lobby/CreateRoomModal/CreateRoomModal.tsx, components/lobby/CreateRoomModal/GameListModal/GameList/GameItem.tsx, requests/rooms/index.ts
- Using `handlePasswordKeyUp` and `handlePasswordChange` simultaneously caused potential repeated input. 
As shown in the following GIF:
| Before | After |
|-----|-------|
|![before](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/16a1dce6-adee-4457-b1d0-e042a49664a4)|![after](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/a78152ae-093f-41db-bd84-65436f3ae1a6)|
- feat: optimized the UX of password input in the private room field.
- fix: fixed the issue that it would submit 3 digits when the password type is number.
- fix: removed the potential for repeated input of the password.
- refactor: added more handlers in the handlePasswordKeyUp function.
- style: added a `div` to wrap input fields to avoid the error message being flex between input.
-
- …
=> fix: some password input issues in create room

docker/Dockerfile.production, next.config.js, package.json, yarn.lock
- refactor `@next/bundle-analyzer` to lazy load because it is a `devDependencies`，if we use production `node_modules` it will cause build failed because `@next/bundle-analyzer` is not installed
- the build error cause by the latest version of `cypress`, so I pin its version now. (In the future, we will rely [Renovate](https://github.com/Game-as-a-Service/Game-Lobby-Web/pull/124) to help us upgrade dependencies and pin to certain version)
- I found that `next build` also need `devDependencies` like `typescript` & `@types/xxx`, so I refactor the Dockerfile to two phase, and the first step will install packages as development mode
-
-
-
=> fix: production docker file build error

.github/workflows/build-and-deploy.yaml
- Consistency
- With docker, we don't have to worry about environment issues.
- Isolation
- Docker containers are isolated from each other and from the host system. Since we host frontend and backend together, it's vital to isolate.
- Automation
- Re-run the container every time we restart the EC2.
- Integration with modern deployment practices
- In the future, we can integrate with Kubernetes or other tools.
- Containerize build and deploy workflow
- Using ECR to store the docker image.
-
-
=> refactor(cicd): containerize build-and-deploy

.github/workflows/ci.yaml, .gitignore, .knip.json, package.json, scripts/knipScanReporter.js, yarn.lock
- [knip](https://github.com/webpro/knip) is a tool which can find unused files, dependencies and exports in JavaScript and TypeScript projects. And this is what linters like `EsLint` can not do because they handle files in isolation.
- The advantages of using `knit` are that less code and dependencies lead to improved performance & bundle size, less maintenance and easier refactorings
-  `knit` has many plugins we can extend, the config is set in [.knip.json](https://github.com/Game-as-a-Service/Game-Lobby-Web/pull/125/files#diff-b4b2f7ddc3de55e1b7051a88b59335a0c31fc287600652a76b8b25d57326cb14), and it will catch these issues:
1.   `Unused files`
2.   `Unused dependencies`
3.   `Unused devDependencies`
4.   `Unlisted dependencies`
5.   `Unlisted binaries`
6.   `Unresolved imports`
7. …
=> feat: knip scan workflow

package.json, yarn.lock
Some times when many members update package.json & add new dependencies, `yarn.lock` will conflict. However, after resolve the conflict, `yarn build` have a high chance to fail because of type error reported by `@types/react`. (It happened many times...)
The root cause is some dependencies use `@types/react` as peer dependency, and their are different version of it in our project
after pin the version and add the version in `yarn resolution` section, there are only one version of `@types/react` in our project
-
-
-
=> fix: pin @types/react & use yarn resolution

components/shared/Tabs/Tab.tsx, components/shared/Tabs/Tabs.stories.tsx, components/shared/Tabs/Tabs.tsx, containers/room/RoomListView.tsx, pages/rooms.tsx
- Simplify code for room list switching using Tabs component
- Update key type of Tabs component to be generic
- Remove unnecessary useEffect and useState syntax
- Manual testing only.
- #127 
`RoomListView` 是一個會接收 props 有 status 屬性的元件，當元件錨定時，會透過 usePagination hook 將 status 作為參數向後端拿取房間列表。
在原本的寫法中， `RoomListView` 會使用 useState 建立一組初始值為 props.status 的狀態，並使用 useEffect 監聽 props.status ，當 props.status 有變化時，則呼叫 setState 改變前述建立的 status 狀態，重點程式碼如下：
```
const RoomsListView: FC<Props> = ({ status }) => {
const [roomStatus, setRoomStatus] = useState<RoomType>(status);
　...
useEffect(() => {
setRoomStatus(status);
}, [status]);
　...
}
```
上述程式碼個人有兩個想法，以下說明：
1.  依照現行需求，使用上述程式碼的目的，猜測是為了希望當 props.status 的值有變換時，要重新依據新的 status 執行 API 以取得不同狀態的房間列表，但這樣的寫法是無效且不必要的，原因以下說明：
　(1) 無效的原因是，元件將 status 作為參數給 …
=> ✅refactor: rooms

.github/workflows/build-and-deploy.yaml, docker/Dockerfile.production, next.config.js, package.json, yarn.lock
- In [previous PR](https://github.com/Game-as-a-Service/Game-Lobby-Web/pull/70), we optimize the image size from `3.4GB` to `871 MB`, and in this PR, we reduce the size again to `216MB` through nextjs's [output tracing](https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files)
- we know that docker have so called `layer cache`, but in previous version of workflow, because docker image will be built in different runner machine, the layer cache will miss. This is why we use `docker/build-push-action@v4` to leverage remote cache in gha. (we can find that the new `Dockerfile` add more layer then before, if the `package.json` & `yarn.lock` not change, it will skip the installation process while building image, which can improve the build speed very …
=> refactor: reduce docker image size by next output tracing

components/rooms/RoomButtonGroup.tsx
- The host doesn't need a 'Ready' button
- Modify RoomButtonGroup Component
- 
- #206
=> refactor: hide 'Ready' button when the user is the host

.github/workflows/ci.yaml
- for now, I find that the CI workflow take too long to execute, it is because upload & download `artifact`  take too much time
- I extract a `init` step to handle downloading & caching  of dependencies, and add `lhci` scan directly in `build` step.
| Old Version (⏰ Time spent: about 8 mins - 10 mins) | New Version (⏰ Time spent: about 3 mins) |
|-----|-------|
| ![圖片](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/35811214/78db5482-f04c-4906-b9a7-076e6fcd15a2) | ![圖片](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/35811214/b2e8f135-027d-43ae-8171-c55bc732a7ff) |
-
-
-
=> refactor: redefine CI workflow steps

components/lobby/UserInfoModal.tsx
- Users still can do others action after pending.
- Added loading condition on Input / Modal / Button component.
- Added useToast hook to handle notification.
-
- #184
=> fix: userinfomodal loading disable other actions

components/lobby/UserInfoModal.tsx
- Not allowed user to change email
- Removed able to change email
-
- Closed #217
=> 👁️ fix: email read only in UserInfoModal

containers/util/Startup.tsx
- Because of the api protected the `authentication`(require Bearer token), it cause error after login.
- The authentication is POSTed every time we refresh, but we still haven't clarified the refresh workflow.
- We should understand why authentication exists, when we need to request it, and how to handle the data after receiving the response.
- temporarily remove the authentication POST request.
-
-
=> :bug: fix(auth): tmp rm authentication

.vscode/settings.json, components/rooms/RoomChatroom/RoomChatroom.tsx, containers/provider/ChatroomProvider.tsx, containers/provider/SocketProvider.tsx, containers/util/Startup.tsx, contexts/ChatroomContext.tsx, contexts/SocketContext.tsx, hooks/context/useSocketCore.ts, package.json, pages/_app.tsx, pages/api/mock/socket.ts, pages/api/mock/socketio.ts, yarn.lock
- ... [PR 249](https://github.com/Game-as-a-Service/Game-Lobby-Web/pull/249#issue-1806544895) 
- Moved Socket Constants to file `@/contexts/SocketContext`
- Encapsulated connect logic to function to be used flexibly in other components
- Added console in mock socket server to show online (dev mode) users
- Follow our codestyle to new `useSocketCore.ts` .
- Encapsulate connect logic in `SocketProvider.ts` as a function.
- Move Socket some constants to `SocketContext.tsx`
-
- #239 
- #249
=> refactor: socket.io infra and decouple ws and chatroom

containers/provider/AuthProvider.tsx, containers/room/RoomListView.tsx, hooks/useUser.ts, pages/auth/login.tsx, pages/auth/token/[token].tsx, pages/login.tsx, pages/rooms/[roomId]/index.tsx
- [Discussion](https://github.com/Game-as-a-Service/Game-Lobby-Web/discussions/260)
- The context gets reset when switching between page components that do not use the serverSideTranslations function to load staticProps
- Reference: [i18next #1683](https://github.com/i18next/next-i18next/issues/1683)
- Apply serverSideTranslations function to every page component.
- Fix some ESLint warning.
-
-
=> fix: context lost after navigated

containers/provider/SocketProvider.tsx
- The CI pipeline is currently failing due to the absence of the mock Sokcet.IO server during CI mode. 
- Modified the WebSocket server configuration logic to ensure the mock Sokcet.IO server is started not only in development mode but also in CI mode.
-
- #270 
-  #261 感謝 @ttpss930141011 在此 PR 中數次分享測試的結果，縮小了釐清本次議題所需要思考的範籌，沒有你的分享可能不會這麼快想到解方。
=> fix: LHCI Failure

package.json, yarn.lock
- An unexpected error occurred while storybook was starting.
|  Previous   | Current |
|  ----  | ----  |
| ![螢幕擷取畫面 2023-08-13 143718](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/bd9d3d36-5d87-405e-aa7f-50aacbffb00a)  | ![image](https://github.com/Game-as-a-Service/Game-Lobby-Web/assets/23444218/4e215c17-8861-46ac-bf5d-680bfa894d22) |
- This error will occur when Next.js upgrades to ~13.4. Relevant issue: [Issue23648](https://github.com/storybookjs/storybook/issues/23684), [Issue23314](https://github.com/storybookjs/storybook/issues/23314)
- Update `@storybook/addon-essentials` from version `7.0.23` to `7.2.3`
- Update `@storybook/addon-interactions` from version `7.0.23` to `7.2.3`
- Update `@storybook/addon-links` from version `7.0.23` to `7.2.3`
- Update …
=> fix: update Storybook packages to version 7.2.3

components/lobby/CreateRoomModal/CreateRoomModal.tsx, requests/rooms/index.ts, yarn.lock
- Fixed no password when create public room
-
-
- #263
=> fix: create public room no password

hooks/usePagination.ts, pages/api/mock/rooms.ts, requests/rooms/index.ts
- The root cause of this problem stems from incorrespondence API formats.
- Redefine the response type of Get/rooms according to [Swagger ](https://api.gaas.waterballsa.tw/swagger-ui/index.html#/game-registration-controller/findGameRegistrations)
-
- #281
=> fix: #281-RoomListView render error

components/rooms/RoomChatroom/RoomChatroom.tsx, containers/provider/SocketProvider.tsx, contexts/SocketContext.tsx, pages/api/mock/socketio.ts
- We didn't add disconnect action when page refresh or leave. It caused server will keep unuse socket connections.
- We didn't add **reconnectionDelay** in socket config. It caused backend developr feel hard when debugging.
- We didn't add **autoConnect** in socket config. It caused some unstable connections when we manually handle connect like us.
- Add **beforeunload EventListener** to handle refreshing or leaving state.
- Add reconnectionDelay & autoConnect in socket config.
-
- #285 
原本這個分支是想用來試試看將 Socket 放進 Store 持久化，結果遇到兩個困難：
1. Zustand Store definition is pure JS. 無法在連接時 addWsHistory Event，硬要使用也是套一個 HOC，那我就用維持現狀就好啦
> Ref: [Zustand document](https://docs.pmnd.rs/zustand/getting-started/comparison#redux) , https://github.com/pmndrs/zustand/discussions/1308
2. 如 @Yuwen-ctw …
=> fix: socket couldn't disconnect during leaving or refreshing page

hooks/usePagination.ts
- To ensure accurate data listing, unify the initial page number from 1 to 0.
- 
-
- Closes  #287
=> fix: modify DEFAULT_PAGE from 1 to 0 in usePagination hook

next-i18next.config.js
- i18n not working in production
- next-i18next.config.js
-
- Close #291
=> fix i18n not working in production issue

docker/Dockerfile.production
- 修正 Production 版 i18n 設定檔未生效問題
-
-
- Close #291
=> fix i18next configuration not taking effect

next-i18next.config.js
- production i18n not match language json file
-
-
- Close #291
=> 🐛 fix i18n production not match json file

.github/dependabot.yml, .github/workflows/auto-label.yaml
- The PR Auto Labeler / label (pull_request) CI in PR rised by [dependabot](https://github.com/apps/dependabot) would fail.
- We didn't accept the PR title `chore(deps): ` in auto-label workflow.
- In order to follow this rule of naming dependent robots, I added `[DEPENDA-BOT] ` in dependabot config file, and added labelsRules in auto-label.ci to detect PR prefix.
> ref: [commit-message](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)
-
- #301
=> fix: dependabot ci failure issue

next.config.js
- Fixing the issue of external images not displaying.
- Reducing server traffic generated by image optimization.
- next.config.js
-
- Close #316 
關於之前說 image 優化是否會造成 server 流量增加，我後來查閱了官方文件與原始碼，發現使用外部圖片時，會 fetch 外部圖片並進行圖片優化，故應該是會造成 server 流量增加，所以目前的解決方案改成取消圖片優化 (image optimization) 這個功能，未來如果有效能問題或想優化本地圖片，可以慢慢針對特定圖片進行優化，如 `<Image unoptimized={false} />`。
- [minimizing-image-optimization-costs](https://vercel.com/docs/image-optimization/managing-image-optimization-costs#minimizing-image-optimization-costs)
- [billing](https://vercel.com/docs/image-optimization/limits-and-pricing#billing)
- [image-optimizer](https://github.com/vercel/next.js/blob/v12.0.10/packages/next/server/image-optimizer.ts#L233)
=> fix: 🔧 unset image optimization

components/rooms/RoomChatroom/RoomChatroom.tsx, containers/provider/SocketProvider.tsx, contexts/SocketContext.tsx, pages/api/mock/socketio.ts
- Socket.IO connects with the jwt token
- When the user's token changes, Socket.IO will automatically reconnect using the new token.
- Socker.IO dev server can get token
-
- Close #318
原本的 Socket.IO 是固定參數，這次需求改為動態帶 auth token
https://socket.io/docs/v4/middlewares/#sending-credentials
=> feat: Socket.IO connects with the jwt token

components/shared/Avatar/Avatar.tsx
- fix production external images not displaying
-
- Avater component image
- Close #316 
不知道為什麼部屬在預覽網站可以正常顯示照片，部屬到正式機後卻沒吃到 `next.config.js` 的 image unoptimized 設定，所以我目前先暫時調整 Avater 裡面的 image 個別設定 unoptimized，有時間再研究為什麼 `next.config.js` 的 `unoptimized` 設定會失效
=> 🐛 fix production external images not displaying

pages/_document.tsx, styles/global.css, tailwind.config.js
- New design system released.
- add tailwindCSS config
- modify body backgound
-
- #193 
- 顏色定義為與 figma 相同的 `primary`, `secondary`, `error`, `gray` and `basic`
- 添加 `fz-{數字}` 來定義字型大小與行高以符合設計稿並方便使用
- 添加 `gradient-purple`, `gradient-black` 背景漸層色
- 添加 `border-gradient-purple` 為 border 漸層色
=> feat: 🧱 add design system

pages/auth/token/[token].tsx
- Changed implementation due to an issue where the token retrieved from query was not as expected
- Replaced `useRouter().query` with `useRouter().asPath` to retrieve the `token` parameter
-
- close #390
=> fix: use useSearchParams for token retrieval instead use useRouter

components/shared/Header.tsx, components/shared/Sidebar.tsx, containers/layout/AppLayout.tsx, hooks/useRequest.ts, pages/index.tsx, tailwind.config.js
- 調整成 V2 版本的樣式
- 調整 layout 按鈕的定義
- Header
- Sidebar
- Layout
- TailwindCSS config
- 樣式調整，手動測試
- #378
=> refactor: layout style and button

components/shared/SearchBar/SearchBar.tsx, components/shared/SearchBar/searchBar.stories.tsx, components/shared/SearchBar/searchBar.test.tsx
- update search bar component v2
- search bar
- update search bar unit test
-
=> feat: update search bar

containers/room/RoomListView.tsx
- when user enter and leave the room page, they can not go back through current rooms page ui
- check room info first, if success, means the user is already been in the room
- try to previous process otherwise.
- fetch api will alert status 400 in the console even catch it
-
=> feat: try to read room info first before join room

components/rooms/GameWindow.tsx, components/shared/Chat/v2/Chat.tsx, containers/layout/AppLayout.tsx, hooks/useChat.ts, hooks/useUser.ts, pages/_document.tsx, pages/auth/token/[token].tsx, pages/index.tsx, pages/rooms/[roomId]/index.tsx, styles/global.css
- 調整整體網站樣式
- 調整進遊戲房間的流程
- 大廳頁面
- 遊戲房間頁面與元件
- 全域共用 header, sidebar
- none
- #399 
- Close #343
=> refactor: website style

.github/workflows/auto-label.yaml
- exclude dependabot from PR auto-label workflow
- auto-label workflow
- none
- none
=> feat: exclude dependabot from PR auto-label workflow

containers/provider/ChatroomProvider.tsx, containers/provider/SocketProvider.tsx, contexts/SocketContext.tsx, hooks/context/useChatroomService.ts, hooks/context/useSocketCore.ts, hooks/useRoomService.ts, services/socket/BaseSocketService.ts, services/socket/ChatSocketService.ts, services/socket/GameSocketService.ts, services/socket/README.md, services/socket/RoomSocketService.ts, services/socket/SocketService.ts, services/socket/index.ts, services/socket/types.ts, services/socket/utils.ts
This PR refactors the chatroom-related components to adopt the new SocketService architecture, improving modularity and maintainability.
- **ChatroomProvider**: Replaced `useChatroomCore` with `useChatroomService`.  
- **SocketProvider**:  
- Now initializes and manages socket connections via `SocketService`.  
- Ensured backward compatibility by keeping the raw socket reference.  
- Improved event handling using `SocketService` methods.  
- **SocketContext & Hooks**: Updated to support the new service-based approach.  
This refactor makes it easier to extend and manage WebSocket connections while reducing direct socket dependencies across the codebase. 
- https://github.com/Game-as-a-Service/Game-Lobby-Web/issues/421
=> refactor: Migrate Chatroom to Socket Service Architecture

.github/workflows/build-and-deploy-storybook.yaml, components/shared/Header.tsx, containers/layout/AppLayout.tsx, containers/provider/SocketProvider.tsx, contexts/SocketContext.tsx, services/socket/index.ts
- 用戶需要知道實時連接狀態，以便了解網路問題或服務中斷
- 當 socket 斷線時，用戶無法知道為何部分功能無法正常運作
- 目前沒有視覺化方式顯示 socket 連接狀態
- 新增socket連接狀態指示器組件，包含四種狀態：連線中、已連線、已斷線、連線錯誤
- 在 Header 組件中添加了 socketStatusIndicator 插槽，用於顯示連接狀態
- 在 AppLayout 中實現 socket 狀態監聽，並根據連接事件更新狀態
- 用不同顏色區分不同連接狀態：綠色(已連線)、紅色(已斷線)、黃色(錯誤)、灰色(連線中)
- 測試各種網路狀況下的狀態指示器行為
- 確保在socket連接、斷開和錯誤時正確顯示對應狀態
- 確認在不同設備和螢幕尺寸下的顯示效果
- 檢查無障礙性支持，確保狀態變更有足夠的對比度和可讀性
- none
=> feat: Implement socket connection status indicator in Header
